### ISSUE TITLE
Schema compilation fails when using bun as package manager

### ISSUE THREAD

**Issue by cassis163** [orval-labs/orval#1454]
## What are the steps to reproduce this issue?

1. Use bun 1.1.13
2. bun create vite@5.2.0 --template=react-swc-ts
3. Install orval 6.30.2
4. Try anything, this was my config file:
```
import { defineConfig } from "orval";

export default defineConfig({
  "backend-api": {
    output: {
      mode: "single",
      target: "src/generated/api.ts",
      schemas: "src/generated/model",
      client: "swr",
      // mock: true,
      override: {
        mutator: {
          path: "src/api/axios-instance.ts",
          name: "customInstance",
          default: true,
        },
      },
    },
    input: {
      target: "http://localhost:8080/api/v3/api-docs",
    },
  },
});

```

## What happens?
Syntax error emerges when the program tries to compile a schema after calling it.

## What were you expecting to happen?
I was expecting to Orval generate some types.

## Any logs, error output, etc?
```
➜ bun run gen:api  
$ orval --config orval.config.ts
Error compiling schema, function code: const schema16 = scope.schema[10];return function validate14(data, {instancePath="", parentData, parentDataProperty, rootData=data}={}){let vErrors = null;let errors = 0;if((!(data && typeof data == "object" && !Array.isArray(data))) && (data !== null)){const err0 = {instancePath,schemaPath:"#/type",keyword:"type",params:{type: schema16.type},message:"must be object,null"};if(vErrors === null){vErrors = [err0];}else {vErrors.push(err0);}errors++;}if(data && typeof data == "object" && !Array.isArray(data)){for(const key0 in data){if(!(key0 === "keyedBy")){const err1 = {instancePath,schemaPath:"#/additionalProperties",keyword:"additionalProperties",params:{additionalProperty: key0},message:"must NOT have additional properties"};if(vErrors === null){vErrors = [err1];}else {vErrors.push(err1);}errors++;}}if(data.keyedBy !== undefined){if(typeof data.keyedBy !== "string"){const err2 = {instancePath:instancePath+"/keyedBy",schemaPath:"#/properties/keyedBy/type",keyword:"type",params:{type: "string"},message:"must be string"};if(vErrors === null){vErrors = [err2];}else {vErrors.push(err2);}errors++;}}}if(errors > 0){const emErrors0 = {"type":[]};for(const err3 of vErrors){if(((((({"str":"err3"}.keyword !== "errorMessage") && (!{"str":"err3"}.emUsed)) && ({"str":"err3"}.instancePath === instancePath)) && ({"str":"err3"}.keyword in {"str":"emErrors0"})) && ({"str":"err3"}.schemaPath.indexOf("#") === 0)) && (/^\/[^\/]*$/.test({"str":"err3"}.schemaPath.slice(1)))){{"str":"emErrors0"}[{"str":"err3"}.keyword].push({"str":"err3"});{"str":"err3"}.emUsed = true;}}for(const key1 in emErrors0){if({"str":"emErrors0"}[{"str":"key1"}].length){if(vErrors === null){vErrors = [{"str":"err4"}];}else {vErrors.push({"str":"err4"});}errors++;}}const emErrs0 = [];for(const err5 of vErrors){if(!{"str":"err5"}.emUsed){{"str":"emErrs0"}.push({"str":"err5"});}}vErrors = emErrs0;errors = {"str":"emErrs0"}.length;}validate14.errors = vErrors;return errors === 0;}
/Users/somedude/Projects/project-top-secret/frontend/node_modules/@stoplight/spectral-core/node_modules/ajv/dist/compile/index.js:120
        throw e;
        ^

SyntaxError: Unexpected token ':'
    at new Function (<anonymous>)
    at Ajv.compileSchema (node_modules/@stoplight/spectral-core/node_modules/ajv/dist/compile/index.js:89:30)
    at Ajv._compileSchemaEnv (node_modules/@stoplight/spectral-core/node_modules/ajv/dist/core.js:473:37)
    at Ajv.compile (/node_modules/@stoplight/spectral-core/node_modules/ajv/dist/core.js:160:38)
    at createRulesetFunction (node_modules/@stoplight/spectral-core/dist/ruleset/function.js:68:80)
    at Object.<anonymous> (node_modules/@stoplight/spectral-functions/dist/alphabetical.js:30:61)
    at Module._compile (node:internal/modules/cjs/loader:1434:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1518:10)
    at Module.load (node:internal/modules/cjs/loader:1249:32)
    at Module._load (node:internal/modules/cjs/loader:1065:12)

Node.js v22.2.0
error: script "gen:api" exited with code 1
```

## Any other comments?
No

## What versions are you using?

**Operating System: MacOS** 
**Package Version: 6.30.2**

**Comment by cassis163** [comment]
Is possibly related to:

- https://github.com/anymaniax/orval/issues/326
- https://github.com/anymaniax/orval/issues/320

**Comment by melloware** [comment]
yeah @cassis163 i think its definitely related to those.

**Comment by soartec-lab** [comment]
Hi, @cassis163 
Hmm, what happens if you explicitly install "ajv"?

```
bun add -D ajv
bun run gen:api
```

**Comment by cassis163** [comment]
Hello @soartec-lab , still the same exact issue.
```
➜ bun run gen:api
$ orval --config orval.config.ts
Error compiling schema, function code: const schema16 = scope.schema[10];return function validate14(data, {instancePath="", parentData, parentDataProperty, rootData=data}={}){let vErrors = null;let errors = 0;if((!(data && typeof data == "object" && !Array.isArray(data))) && (data !== null)){const err0 = {instancePath,schemaPath:"#/type",keyword:"type",params:{type: schema16.type},message:"must be object,null"};if(vErrors === null){vErrors = [err0];}else {vErrors.push(err0);}errors++;}if(data && typeof data == "object" && !Array.isArray(data)){for(const key0 in data){if(!(key0 === "keyedBy")){const err1 = {instancePath,schemaPath:"#/additionalProperties",keyword:"additionalProperties",params:{additionalProperty: key0},message:"must NOT have additional properties"};if(vErrors === null){vErrors = [err1];}else {vErrors.push(err1);}errors++;}}if(data.keyedBy !== undefined){if(typeof data.keyedBy !== "string"){const err2 = {instancePath:instancePath+"/keyedBy",schemaPath:"#/properties/keyedBy/type",keyword:"type",params:{type: "string"},message:"must be string"};if(vErrors === null){vErrors = [err2];}else {vErrors.push(err2);}errors++;}}}if(errors > 0){const emErrors0 = {"type":[]};for(const err3 of vErrors){if(((((({"str":"err3"}.keyword !== "errorMessage") && (!{"str":"err3"}.emUsed)) && ({"str":"err3"}.instancePath === instancePath)) && ({"str":"err3"}.keyword in {"str":"emErrors0"})) && ({"str":"err3"}.schemaPath.indexOf("#") === 0)) && (/^\/[^\/]*$/.test({"str":"err3"}.schemaPath.slice(1)))){{"str":"emErrors0"}[{"str":"err3"}.keyword].push({"str":"err3"});{"str":"err3"}.emUsed = true;}}for(const key1 in emErrors0){if({"str":"emErrors0"}[{"str":"key1"}].length){if(vErrors === null){vErrors = [{"str":"err4"}];}else {vErrors.push({"str":"err4"});}errors++;}}const emErrs0 = [];for(const err5 of vErrors){if(!{"str":"err5"}.emUsed){{"str":"emErrs0"}.push({"str":"err5"});}}vErrors = emErrs0;errors = {"str":"emErrs0"}.length;}validate14.errors = vErrors;return errors === 0;}
/Users/me/Projects/project-x/frontend/node_modules/@stoplight/spectral-core/node_modules/ajv/dist/compile/index.js:120
        throw e;
        ^

SyntaxError: Unexpected token ':'
    at new Function (<anonymous>)
    at Ajv.compileSchema (/Users/casper.aangeenbrug/Projects/project-zuidbos/frontend/node_modules/@stoplight/spectral-core/node_modules/ajv/dist/compile/index.js:89:30)
    at Ajv._compileSchemaEnv (/Users/casper.aangeenbrug/Projects/project-zuidbos/frontend/node_modules/@stoplight/spectral-core/node_modules/ajv/dist/core.js:473:37)
    at Ajv.compile (/Users/casper.aangeenbrug/Projects/project-zuidbos/frontend/node_modules/@stoplight/spectral-core/node_modules/ajv/dist/core.js:160:38)
    at createRulesetFunction (/Users/casper.aangeenbrug/Projects/project-zuidbos/frontend/node_modules/@stoplight/spectral-core/dist/ruleset/function.js:68:80)
    at Object.<anonymous> (/Users/casper.aangeenbrug/Projects/project-zuidbos/frontend/node_modules/@stoplight/spectral-functions/dist/alphabetical.js:30:61)
    at Module._compile (node:internal/modules/cjs/loader:1434:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1518:10)
    at Module.load (node:internal/modules/cjs/loader:1249:32)
    at Module._load (node:internal/modules/cjs/loader:1065:12)

Node.js v22.2.0
error: script "gen:api" exited with code 1
```

**Comment by soartec-lab** [comment]
@cassis163 

Oh...thanks for trying. Actually, I had the same problem and I solved it by explicitly installing `ajv`. The problem has been resolved since `v1.1.11`.

https://bun.sh/blog/bun-v1.1.11#fixed-bun-install-peer-dependencies-resolution

I haven't reproduced it in my project using `Bun` v1.1.13 and `orval` 6.30.2.

**Comment by 1nVitr0** [comment]
Had the same issue using node `20.17.0` and npm `10.8.2` after upgrading some unrelated dependencies. Running `npm i -D ajv` "fixed" it for me, though `npm i -D ajv@8.12` (the version set in orval's dependencies) did not.

Wasn't able to reporoduce it in a minimal (not) working example unfortunately.

**Comment by emanuelet** [comment]
For me running the `orval` command with `npx` fixed the issue, without having to install `ajv` or what not

**Comment by loicnestler** [comment]
For me the issue remains; both when running with `bun` and when running with `npx`. 
I've also tried to install `ajv` (both `ajv@latest` as well as `ajv@8.12`). Both solutions don't work.
Any quick fix for that?

**Comment by isoroka-plana** [comment]
I just ran into the same issue. And fllowing the steps listed in EDIT of @loicnestler's message I got it to work again 🤷

**Comment by soartec-lab** [comment]
I gonna update `ajv` to latest in `orval` later.

**Comment by soartec-lab** [comment]
I try update `ajv` to latest version in #1771.
If the problem persists, please reopen this issue.

**Comment by mrctrifork** [comment]
As per today I face the same issue.

Bun 1.2.7 and latest orval

**Comment by melloware** [comment]
@mrctrifork i reopened.

**Comment by mrctrifork** [comment]
I have just tried it and it seems it might not be just bun.

Using `node 18.16.1`:

```bash
mkdir testing-orval/
cd testing-orval/
npm init -y
npm i orval --save-dev
# write orval.config.ts what I shared in https://github.com/orval-labs/orval/issues/1904#issuecomment-2764747089
npx orval
```

![Image](https://github.com/user-attachments/assets/8650f806-4e96-49ce-9df1-80f5a736f07e)

**Comment by mrctrifork** [comment]
Sorry for my last comment; i got the contents of the files mixed. It appears to be working on node but not on bun as this issue already claims 🙏🏻

**Comment by mrctrifork** [comment]
After running some tests:

Using `npm i orval --save-dev` instead of `bun i --dev` makes it work. This is likely to not be a problem with the lib itself but rather something related to bun and the way it handles postinstall or something alike

**Comment by OiAnthony** [comment]
I tried `bun add -D ajv`, then deleted `node_modules` and reinstalled the dependencies, and it worked!

**Comment by mrctrifork** [comment]
bun version?

**Comment by sd44** [comment]
> I tried `bun add -D ajv`, then deleted `node_modules` and reinstalled the dependencies, and it worked!
> 
> bun version: v1.2.9 orval version: v7.8.0 ajv version: v8.17.1

It solved the same issue for me， thx.

 bun version: v1.2.10 orval version: v7.9.0 ajv version: v8.17.1

**Comment by melloware** [comment]
We just released 8.0.0-rc.0 which is fully ESM if you would like to retest please and report back.

**Comment by mrctrifork** [comment]
Hey, I've gotten around trying this and it worked. Thanks a ton @melloware 

I ran:

```bash
bunx --bun orval@8.0.0-rc2
```

**Comment by melloware** [comment]
Awesome!

**Comment by RobbyUitbeijerse** [comment]
Hey @melloware , I think this is partially fixed but no luck when using a local orval config here.

For example, this seems to work fine:

```
bunx --bun orval@8.0.0-rc.2 --input https://cddapitrial.azurewebsites.net/swagger/v4/swagger.json --output ./src/services/scope/client.generated.ts
```

But when running

```
bunx --bun orval@8.0.0-rc.2 --config ./orval.config.ts
```

Or by calling the local bin through the locally installed package (installed through bun)

```
"generate:scope:client": "orval --config ./orval.config.ts",
```


I always land in the following:


```
$ bunx --bun orval@8.0.0-rc.2 --config ./orval.config.ts
🍻 orval v8.0.0-rc.2 - A swagger client generator for typescript
Error compiling schema, function code: const schema16 = scope.schema[10];return function validate14(data, {insta
```



Just in case, here's my current orval.config.ts to illustrate I'm not doing anything fancy there

```
import "dotenv/config";
import { defineConfig } from "orval";

export default defineConfig({
  "scope-api": {
    input: {
      target: "https://cddapitrial.azurewebsites.net/swagger/v4/swagger.json",
    },
    output: {
      baseUrl: process.env.SCOPE_API_URL,
      client: "fetch",
      target: "./src/services/scope/client/client.generated.ts",
    },
  },
});

```

And I'm definitely on the right version locally:

<img width="453" height="213" alt="Image" src="https://github.com/user-attachments/assets/14268f78-5060-49d6-9c8c-7d5792ad7898" />

**Comment by dream2333** [comment]
> Hey [@melloware](https://github.com/melloware) , I think this is partially fixed but no luck when using a local orval config here.嘿，我觉得这部分已经修复了一些，但在这里使用本地的 orval 配置时却没有好运。
> 
> For example, this seems to work fine:例如，这似乎可以正常工作：
> 
> ```
> bunx --bun orval@8.0.0-rc.2 --input https://cddapitrial.azurewebsites.net/swagger/v4/swagger.json --output ./src/services/scope/client.generated.ts
> ```
> 
> But when running  但在运行时
> 
> ```
> bunx --bun orval@8.0.0-rc.2 --config ./orval.config.ts
> ```
> 
> Or by calling the local bin through the locally installed package (installed through bun)或通过本地安装的包（通过 bun 安装）调用本地二进制文件
> 
> ```
> "generate:scope:client": "orval --config ./orval.config.ts",
> ```
> 
> I always land in the following:我总是陷在以下情况：
> 
> ```
> $ bunx --bun orval@8.0.0-rc.2 --config ./orval.config.ts
> 🍻 orval v8.0.0-rc.2 - A swagger client generator for typescript
> Error compiling schema, function code: const schema16 = scope.schema[10];return function validate14(data, {insta
> ```
> 
> Just in case, here's my current orval.config.ts to illustrate I'm not doing anything fancy there以防万一，这里是我当前的 orval.config.ts，以说明我并没有在那里做任何花哨的事情。
> 
> ```
> import "dotenv/config";
> import { defineConfig } from "orval";
> 
> export default defineConfig({
>   "scope-api": {
>     input: {
>       target: "https://cddapitrial.azurewebsites.net/swagger/v4/swagger.json",
>     },
>     output: {
>       baseUrl: process.env.SCOPE_API_URL,
>       client: "fetch",
>       target: "./src/services/scope/client/client.generated.ts",
>     },
>   },
> });
> ```
> 
> And I'm definitely on the right version locally:而且我在本地肯定使用的是正确的版本：
> 
> <img alt="Image" width="453" height="213" src="https://private-user-images.githubusercontent.com/10176709/518204974-14268f78-5060-49d6-9c8c-7d5792ad7898.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Njc3NTkwMTQsIm5iZiI6MTc2Nzc1ODcxNCwicGF0aCI6Ii8xMDE3NjcwOS81MTgyMDQ5NzQtMTQyNjhmNzgtNTA2MC00OWQ2LTljOGMtN2Q1NzkyYWQ3ODk4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNjAxMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjYwMTA3VDA0MDUxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM3Y2UyMDFlNGIxZmM5MGM0YWIwNTlmMjdmNzYxOWIyMWM3ZDAyMjMyMTNmODQzZmQ0ZGJlNzA0Y2RhNzAzZmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.cJn7YdNTPY6m5Wiy89c8BmJAIGsX-u2fc0PBbD_Yge8">

same

**Comment by melloware** [comment]
@dream2333 can you try 8.0.0-rc5 also just in case?
